// web/src/lib/components/explorer/TagMigrationDialog.tsx
import { useEffect, useState } from "react";
import { Play } from "lucide-react";
import { toast } from "sonner";
import { fetchAPI } from "$lib/api";
import { Button } from "$lib/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "$lib/components/ui/dialog";
import { useI18n } from "$lib/i18n";

type Props = {
  open?: boolean;
  count?: number;
  onOpenChange?: (open: boolean) => void;
  onComplete?: () => void;
};

export function TagMigrationDialog({ open = false, count = 0, onOpenChange, onComplete }: Props) {
  const { t } = useI18n();
  const [running, setRunning] = useState(false);
  const [status, setStatus] = useState("");
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    if (open && !running) {
      setStatus(t("migration-found-tags", { count }));
      setProgress(0);
    }
  }, [open, running, count, t]);

  function handleOpenChange(next: boolean) {
    if (running && !next) return;
    onOpenChange?.(next);
  }

  async function runTagMigration() {
    setRunning(true);
    setStatus(t("status-migration-init"));
    setProgress(0);

    let hasMore = true;
    let attempts = 0;
    let totalErrors = 0;
    let totalItems = 0;
    let totalProcessed = 0;
    const maxAttempts = 1000;

    while (hasMore && attempts < maxAttempts) {
      attempts++;
      const result = await fetchAPI<{
        processed: number;
        hasMore: boolean;
        total: number;
        errors?: number;
      }>("/api/migration/tags/run-batch", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ batchSize: 3 }),
      });

      if (!result.success || !result.data) {
        setStatus(t("toast-migration-failed") + ": " + (result.error || ""));
        setRunning(false);
        return;
      }

      totalProcessed = result.data.processed;
      hasMore = result.data.hasMore;
      totalItems = result.data.total;
      totalErrors = result.data.errors ?? 0;
      setProgress(totalItems > 0 ? Math.round((totalProcessed / totalItems) * 100) : 0);
      setStatus(t("status-migration-progress", { current: totalProcessed, total: totalItems }));
      if (hasMore) {
        await new Promise((resolve) => setTimeout(resolve, 100));
      }
    }

    if (attempts >= maxAttempts) {
      setStatus(t("migration-stopped"));
      setRunning(false);
      return;
    }

    if (totalErrors > 0) {
      const finalProgress = totalItems > 0 ? Math.round((totalProcessed / totalItems) * 100) : 0;
      setProgress(finalProgress);
      const failedMsg = t("toast-migration-tag-failures", { count: totalErrors });
      setStatus(failedMsg);
      toast.error(failedMsg);
      setRunning(false);
      return;
    }

    setProgress(100);
    setStatus(t("toast-migration-success"));
    toast.success(t("toast-migration-success"));
    setTimeout(() => {
      setRunning(false);
      handleOpenChange(false);
      onComplete?.();
    }, 2000);
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="sm:max-w-md" showCloseButton={!running}>
        <DialogHeader>
          <DialogTitle>{t("modal-migration-title")}</DialogTitle>
        </DialogHeader>
        <div className="space-y-3">
          <p className="text-sm text-muted-foreground">{status}</p>
          <div className="h-2 rounded-full bg-muted overflow-hidden">
            <div
              className="h-full bg-primary transition-all duration-200"
              style={{ width: `${progress}%` }}
            />
          </div>
          <p className="text-xs text-muted-foreground">{t("migration-note")}</p>
        </div>
        {!running ? (
          <DialogFooter>
            <Button onClick={runTagMigration}>
              <Play className="size-3.5" />
              {t("btn-start-migration")}
            </Button>
          </DialogFooter>
        ) : null}
      </DialogContent>
    </Dialog>
  );
}

// web/src/lib/components/explorer/TagMigrationDialog.svelte
<script lang="ts">
  import { toast } from "$lib/toast/toast.svelte";
  import { fetchAPI } from "$lib/api";
  import AppDialog from "$lib/components/ui/app-dialog.svelte";
  import DialogActions from "$lib/components/ui/dialog-actions.svelte";
  import { useI18n } from "$lib/i18n/context.svelte";

  type Props = {
    open?: boolean;
    count?: number;
    onOpenChange?: (open: boolean) => void;
    onComplete?: () => void;
  };

  let { open = $bindable(false), count = 0, onOpenChange, onComplete }: Props = $props();

  const i18n = useI18n();
  let running = $state(false);
  let status = $state("");
  let progress = $state(0);

  $effect(() => {
    if (open && !running) {
      status = i18n.t("migration-found-tags", { count });
      progress = 0;
    }
  });

  function handleOpenChange(next: boolean) {
    if (running && !next) return;
    open = next;
    onOpenChange?.(next);
  }

  async function runTagMigration() {
    running = true;
    status = i18n.t("status-migration-init");
    progress = 0;

    let hasMore = true;
    let attempts = 0;
    let totalErrors = 0;
    let totalItems = 0;
    let totalProcessed = 0;
    const maxAttempts = 1000;

    while (hasMore && attempts < maxAttempts) {
      attempts++;
      const result = await fetchAPI<{
        processed: number;
        hasMore: boolean;
        total: number;
        errors?: number;
      }>("/api/migration/tags/run-batch", {
        method: "POST",
        body: JSON.stringify({ batchSize: 3 }),
      });

      if (!result.success || !result.data) {
        status = i18n.t("toast-migration-failed") + ": " + (result.error || "");
        running = false;
        return;
      }

      totalProcessed = result.data.processed;
      hasMore = result.data.hasMore;
      totalItems = result.data.total;
      totalErrors = result.data.errors ?? 0;
      progress = totalItems > 0 ? Math.round((totalProcessed / totalItems) * 100) : 0;
      status = i18n.t("status-migration-progress", {
        current: totalProcessed,
        total: totalItems,
      });
      if (hasMore) {
        await new Promise((resolve) => setTimeout(resolve, 100));
      }
    }

    if (attempts >= maxAttempts) {
      status = i18n.t("migration-stopped");
      running = false;
      return;
    }

    if (totalErrors > 0) {
      const finalProgress = totalItems > 0 ? Math.round((totalProcessed / totalItems) * 100) : 0;
      progress = finalProgress;
      const failedMsg = i18n.t("toast-migration-tag-failures", { count: totalErrors });
      status = failedMsg;
      toast.error(failedMsg);
      running = false;
      return;
    }

    progress = 100;
    status = i18n.t("toast-migration-success");
    toast.success(i18n.t("toast-migration-success"));
    setTimeout(() => {
      running = false;
      handleOpenChange(false);
      onComplete?.();
    }, 2000);
  }
</script>

<AppDialog
  bind:open
  title={i18n.t("modal-migration-title")}
  class="sm:max-w-md"
  showCloseButton={!running}
  onOpenChange={handleOpenChange}
>
  <div class="space-y-3">
    <p class="text-sm text-muted-foreground">{status}</p>
    <div class="h-2 rounded-full bg-muted overflow-hidden">
      <div
        class="h-full bg-primary transition-all duration-200"
        style={`width: ${progress}%`}
      ></div>
    </div>
    <p class="text-xs text-muted-foreground">{i18n.t("migration-note")}</p>
  </div>
  {#snippet footer()}
    {#if !running}
      <DialogActions
        onCancel={() => handleOpenChange(false)}
        primaryLabel={i18n.t("btn-start-migration")}
        onPrimary={() => void runTagMigration()}
      />
    {/if}
  {/snippet}
</AppDialog>
